### ISSUE TITLE
#include <credentials.h>

### ISSUE THREAD

**Issue by maba64** [SensorsIot/PresenceSimulator#1]
Hallo Andreas
Ich wollte dein Projekt nachbauen. Leider erhalte ich beim kompilieren eine Fehlermeldung: #include <credentials.h> ?
Wäre es möglich  den simulator auch via APP (Android)  ein und auszuschalten ?

Besten Dank für deine riesen Arbeit und deine tollen Videos. So konnte ich schon einiges lernen und habe einige super Tipps erhalten !!!!

Gruss Markus

**Comment by SensorsIot** [comment]
1. Du kannst die Zeile löschen. Dann musst du einfach die Credentials in deinem Sketch eintragen.
2. Das mit dem Android ist vermutlich eine grössere Sache. Da kenne ich mich nicht aus.
